---
- name: Configure System
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.forwarding
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Check System Requirements
  assert:
    that:
      - "ansible_memfree_mb >= {{ item.value.replicas * system_requirements.memory }}"
      - "mount[0].size_available / 1000 / 1000 / 1000 > {{ item.value.replicas * item.value.requirements.disk }}"
    msg: "System requirements are not met"
  vars:
    mount: "{{ ansible_mounts | selectattr('mount','equalto',storage_volume) }}"
  with_items: "{{ services | dict2items}}"

- name: Prepare Directory Tree
  file:
    path: "{{ app_path }}"
    state: directory
    recurse: yes

- name: Deploy Configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: templates/compose.yaml.tmpl, dest: "{{ app_path }}/compose.yaml"}
  register: configuration

- name: Start Application
  shell:
    cmd: "docker stack deploy {{ item.key }} -c compose.yaml"
    chdir: "{{ app_path }}"
  # when: configuration.changed
  with_items: "{{ services | dict2items}}"

- name: Check App
  uri:
    url: "http://{{ host }}:{{ item.value.ports[0].expose_port }}"
    method: "GET"
    return_content: true
  register: tests
  with_items: "{{ services | dict2items }}"

- name: Test Output
  debug:
    msg: "{{ item.content }}"
  with_items: "{{ tests.results }}"
