---
- name: Test
  debug:
    msg: "{{ mount[0] }}"
  vars:
    mount: "{{ ansible_mounts | selectattr('mount','equalto','/export') }}"

- name: Check System Requirements
  assert:
    that:
      - "ansible_memfree_mb >= {{ services.api.replicas * system_requirements.memory }}"
      - "mount[0].size_available / 1000 / 1000 / 1000 > {{ services.api.replicas * system_requirements.disk }}"
    msg: "System requirements are not met"
  vars:
    mount: "{{ ansible_mounts | selectattr('mount','equalto','/export') }}"

- name: Prepare Directory Tree
  file:
    path: "{{ app_path }}"
    state: directory
    recurse: yes

- name: Deploy Configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: templates/compose.yaml.tmpl, dest: "{{ app_path }}/compose.yaml"}
    #- {src: templates/Dockerfile.tmpl, dest: "{{ app_path }}/Dockerfile"}
    - {src: templates/secret-keys-volume.tmpl, dest: "{{ app_path }}/secret-keys_volume"}
  register: configuration

- name: Start Application
  shell:
    cmd: docker stack deploy api -c compose.yaml
    chdir: "{{ app_path }}"
  register: startup

- name: Startup Logs
  debug:
    msg: "{{ startup.stderr_lines }}"

- name: Check App
  uri:
    url: "http://localhost:{{ services.api.ports[0].expose_port }}"
    return_content: true
  register: test

- name: Test Output
  debug:
    msg: "{{ test.content }}"
